#include "stm32f10x.h"                 



/**
  * @brief  Timer Initialization for the whole Furuta Pendulum system 
  * @param  None
  * @retval None
  */
void Timer_Init(void)
{
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_TIM1, ENABLE);
	
	TIM_InternalClockConfig(TIM1);	// Select TIM1 as internal clock, shut down slave mode
	
	TIM_TimeBaseInitTypeDef TIM_TimeBaseInitStructure;
	TIM_TimeBaseInitStructure.TIM_ClockDivision 	= TIM_CKD_DIV1;			// No clock division
	TIM_TimeBaseInitStructure.TIM_CounterMode 		= TIM_CounterMode_Up;	// Upward counting
	TIM_TimeBaseInitStructure.TIM_Period    = 1000 - 1;   // ARR: 1MHz/1000 = 1kHz -> 1ms update
	TIM_TimeBaseInitStructure.TIM_Prescaler = 72 - 1;     // PSC: 72MHz/72 = 1MHz

	TIM_TimeBaseInitStructure.TIM_RepetitionCounter = 0; 
	TIM_TimeBaseInit(TIM1, &TIM_TimeBaseInitStructure);
	TIM_ClearFlag(TIM1, TIM_FLAG_Update);	// Clear the FlAG=1 that generated by shadow register
	
	TIM_ITConfig(TIM1, TIM_IT_Update, ENABLE); // As combination with TIM1_UP_IRQHandler 
	
	NVIC_PriorityGroupConfig(NVIC_PriorityGroup_2);
	
	NVIC_InitTypeDef NVIC_InitStructure;
	NVIC_InitStructure.NVIC_IRQChannel 					 = TIM1_UP_IRQn; // Select IT channel
	NVIC_InitStructure.NVIC_IRQChannelCmd 				 = ENABLE; 
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 2;	 
	NVIC_InitStructure.NVIC_IRQChannelSubPriority 		 = 1;	 
	NVIC_Init(&NVIC_InitStructure);
	
	TIM_Cmd(TIM1, ENABLE);
}



